apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: supp-administrativo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supp-administrativo-frontend
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: supp-administrativo-frontend
        tier: frontend
    spec:
      containers:
        - name: supp-administrativo-frontend
          image: IMAGE_NAME:IMAGE_TAG # Será substituído no momento da implantação (supp-administrativo-frontend.deploy)
          imagePullPolicy: Always #para garantir que ao refazer redeploy da mesma tag, seja recriado o container.
          ports:
            - containerPort: 4200
              protocol: "TCP"
          tty: true
          stdin: true
---
apiVersion: v1
kind: Service
metadata:
  name: supp-administrativo-frontend
  labels:
    app: supp-administrativo-frontend
    tier: frontend
spec:
  ports:
    - name: http
      port: 4200
      targetPort: 4200
      protocol: TCP
  selector:
    app: supp-administrativo-frontend
    tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supp-administrativo-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - supersapiens$(SUFFIX_INGRESS_DNS_ENTRY)
      secretName: "secret-tls"
  rules:
    - host: supersapiens$(SUFFIX_INGRESS_DNS_ENTRY)
      http:
        paths:
          - backend:
              service:
                name: supp-administrativo-frontend
                port:
                  number: 4200
            path: /
            pathType: ImplementationSpecific