export * from './tarefas.selectors';
export * from './folders.selectors';
export * from './lotacao.selectors';
export * from './unidade.selectors';
export * from './setor.selectors';
export * from './assinaturas.selectors';
export * from './componentes-digitais.selectors';
export * from './documentos.selectors';
export * from './documentos-vinculados.selectors';
