apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
    name: angular
spec:
    replicas: 1
    selector:
        matchLabels:
            app: angular
            tier: frontend
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: angular
                tier: frontend
        spec:
            containers:
                - name: angular
                  image: 172.17.24.157:5000/angular-prod:latest
                  ports:
                      - containerPort: 4200
                        protocol: "TCP"
                  tty: true
                  stdin: true
---
apiVersion: v1
kind: Service
metadata:
    name: angular
    labels:
        app: angular
        tier: frontend
spec:
    ports:
        - name: http
          port: 4200
          targetPort: 4200
          protocol: TCP
    selector:
        app: angular
        tier: frontend
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: angular-prod-ingress
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
    rules:
        - host: supp.agu.gov.br
          http:
              paths:
                  - backend:
                        serviceName: angular
                        servicePort: 4200

